spring:
  datasource:
    url: jdbc:h2:mem:${HOME:${HOMEDRIVE}}/onlineTestDB;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_UPPER=false;;NON_KEYWORDS=user
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true